### ISSUE TITLE
Already compressed video taking too much time(mpeg-4 format )

### ISSUE THREAD

**Issue by Mohsin92** [iamkdblue/CompressVideo#1]
Is there any way to identify selected video is compressed or not?

because I have one compressed video mpeg-4  format 24mb size
while compressing it took 10min to compress and quality also hamper.

If we can find selected video is already compress then I can ignore those video.

any help will be highly appreciated.

**Comment by iamkdblue** [comment]
First of all, there to no way to found video is compress or not.
I tried this library, its work well for mp4 videos, I am not aware of mpeg-4 format.
