### ISSUE TITLE
How this library works?

### ISSUE THREAD

**Issue by algavania** [iamkdblue/CompressVideo#3]
I still don't understand how VideoCompress works. After declaring `VideoCompress.compressVideoHigh(FileUtils.getPath(getApplicationContext(), imageUri)` what should I do? I wanna get the compressed file and then change that file to uri.

**Comment by iamkdblue** [comment]
You should try a sample app, just clone the project, and run.

**Comment by algavania** [comment]
Hi, I finally got it. I also made a project based on the sample app, but why in my project the audio is gone after being compressed?

**Comment by algavania** [comment]
Never mind, it works fine when I change my `com.googlecode.mp4parser` to `1.0.6` version. Thanks for responding tho!
